#!/bin/sh
#
REPEAT=$(gum choose 1 2 3 4 5 6)

WORKMSG="Finished ${TIME} Minutes of break time to start again!"
BREAKMSG="Finished ${TIME} Minutes of work good job!"

pomodoro () {
  termdown 50m
  notify-send Pomodoro "${WORKMSG}"

  for i in $(seq 3); do 
    paplay ~/Downloads/alarm.mp3
  done

  notify-send Pomodoro "Starting break"

  termdown 10m

  notify-send Pomodoro "${BREAKMSG}"
  for i in $(seq 3); do 
    paplay ~/Downloads/alarm.mp3
  done

}

for i in $(seq $REPEAT); do
    pomodoro
done
