format = """
$username\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break"""

add_newline = false

[directory]
style = "bold cyan"
truncation_length = 4
read_only=" "

[username]
style_user = "yellow bold"
style_root = "black bold"
format = "[$user]($style) in "
disabled = false
show_always = true

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bold black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](red) ($ahead_behind$stashed )]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

