#!/bin/env bash

killall -q pipewire 
killall -q pipewire-pulse 
killall -q wireplumber 

while pgrep -u $UID -x pipewire >/dev/null; do sleep 1; done
while pgrep -u $UID -x pipewire-pulse >/dev/null; do sleep 1; done
while pgrep -u $UID -x wireplumber >/dev/null; do sleep 1; done

pipewire &
pipewire-pulse &
wireplumber
