pcall(require, "luarocks.loader")
gears = require("gears")
awful = require("awful")
require("awful.autofocus")
wibox = require("wibox")
beautiful = require("beautiful")
naughty = require("naughty")
menubar = require("menubar")
hotkeys_popup = require("awful.hotkeys_popup")
beautiful.init("~/.config/awesome/theme.lua")
require("awful.hotkeys_popup.keys")
require("keys")
require("rules")
require("bar")


awful.spawn.with_shell("~/.config/awesome/scripts/startup")